### ISSUE TITLE
Random bigheads

### ISSUE THREAD

**Issue by Eronheit** [RobertBroersma/bigheads#10]
hello, good job!
It would be very good to be able to generate random bigheads :D

**Comment by DerpyScripts** [comment]
Hey @Eronheit, if you don't set a prop in the `<BigHead />` element, it will choose a random value for it, so if you want a completely random head just don't set any props.
Likewise if you're using the API to load bigheads in an `<img />` element, just don't set any parameters and they will also be chosen at random. (e.g. `<img src="https://bigheads.io/svg" />`)
