### ISSUE TITLE
[Request] Online playground 

### ISSUE THREAD

**Issue by MoKhajavi75** [RobertBroersma/bigheads#14]
Hey

I love this bigheads :grin:

Any chance to have an online playground to generate them in real-time? (Maybe with `png` export too :sunglasses: )

Thanks for all your efforts! :heart:

**Comment by RobertBroersma** [comment]
Hey @MohamadKh75 

Did you take a look at https://bigheads.io/editor/ ?

You can't export them in PNG format directly, but there's an SVG export, which you could easily convert to PNG somewhere online or in your favourite editing tool. You could also use the SVG directly if that fits your needs.

**Comment by MoKhajavi75** [comment]
Well, that's exactly what I asked :grin:
I just didn't find the link or button to it anywhere :thinking:
