### ISSUE TITLE
[Request] Add surgical mask

### ISSUE THREAD

**Issue by MoKhajavi75** [RobertBroersma/bigheads#16]
Due to Covid-19, I guess it's good to have some masks :mask:

It can be added to `accessory` enum :thinking:

**Comment by RobertBroersma** [comment]
Hi Mohamad. Thanks for the suggestion!

There's already a few ideas on my backlog, but a mask would be a great topical addition. I'll try to whip something up!

**Comment by RobertBroersma** [comment]
Face Masks are added in v0.3.0!

Check them out https://bigheads.io/
