### ISSUE TITLE
Playground: Generated image dissapears on with "Mask" set to "False"

### ISSUE THREAD

**Issue by totoroot** [RobertBroersma/bigheads#19]
Hey,

Just stumbled across this and must say, good job! :clap: 

However, I just noticed that the image disappears on playground upon setting "Mask" to "False" in Firefox Developer Edition 82.0b9. It works fine for me on Chromium 86.0.4240.75.
I checked the inspector but couldn't figure out why the image would disappear as it only happens with "Mask" but not with other settings.

On another note the ambiguity of using "mask" for the backdrop might confuse some, now that you have added "faceMask".

Cheers!

**Comment by RobertBroersma** [comment]
Hmm, that's a weird bug indeed. Thanks for reporting!

**Comment by RobertBroersma** [comment]
This is now fixed! Thanks again for the report.
