### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by Haqverdi** [RobertBroersma/bigheads#2]
Thanks for lib)
What about RN support?

**Comment by RobertBroersma** [comment]
Hey @Haqverdi I'm not very experienced with React Native. What would I need to add to support RN?

**Comment by felipecespedes** [comment]
I have created a React Native library for `BigHeads`, I hope you guys find it useful 😄
- [react-native-bigheads](https://github.com/felipecespedes/react-native-bigheads)
