### ISSUE TITLE
Adding new items to bigheads 

### ISSUE THREAD

**Issue by steelwolf180** [RobertBroersma/bigheads#20]
Hi Robert, 
     I was wondering how do you create new components of SVG while laying on top of existing react components. As I tried googling around for it but it seems your route was easy instead of prebuilt tons of SVG. May I know is there a guide or something on adding it while laying on top of these SVG files. Cause I'm looking of implementing something similar as well.

**Comment by RobertBroersma** [comment]
I'm not sure I understand the question, but I think you're asking how to implement the layering of SVG's on top of each other?

SVG files are extended from XML, just like HTML. And just like HTML they can be translated to JSX for usage with React!

You can check my implementation by going over the code in this repo.

**Comment by steelwolf180** [comment]
Yup, your right in terms of layering SVG as React components. I was heading the wall in figuring on how to build the React components that use the self-made SVG code instead of import it as a regularlar SVG file.
