### ISSUE TITLE
Can you come up with a support for nuxt3 or vue3?

### ISSUE THREAD

**Issue by nideajun** [RobertBroersma/bigheads#51]
I think this design concept is very innovative. It would be even better if it could support Vue3 or Nuxt3.

**Comment by RobertBroersma** [comment]
I don't know if it supports Vue 3, but someone made this port: https://github.com/DerpyScripts/vue-bigheads

**Comment by nideajun** [comment]
Thank you very much for your help. I have tried in nuxt3
<script setup lang="ts">
Import {BigHead} from "vue bigheads";
</script>
This quote prompts Vue: Could not find a declaration file for module Vue bigheads.

 It should be Vue2's JavaScript and cannot be directly referenced in TS. But with help, if I have time, I will try to change it to TS. Thank you again for your help.
